// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class AprobacionVacaciones
{
    public int idAprobacionVacacion { get; set; }

    public int? idSolicitudVacacion { get; set; }

    public DateOnly? AprobacionVacacionFecha { get; set; }

    public virtual SolicitudVacaciones idSolicitudVacacionNavigation { get; set; }
}