// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class Contratos
{
    public int idContrato { get; set; }

    public int? FKidEmpleado { get; set; }

    public int? FKidContratoTipo { get; set; }

    public DateOnly FechaInicioContrato { get; set; }

    public DateOnly ContratoFechaFin { get; set; }

    public decimal ContratoSalario { get; set; }

    public bool? EstadoContrato { get; set; }

    public virtual ContratosTipo FKidContratoTipoNavigation { get; set; }

    public virtual Empleados FKidEmpleadoNavigation { get; set; }
}