// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class Inasistencias
{
    public int idLicencia { get; set; }

    public int idEmpleado { get; set; }

    public DateOnly InasistenciaFecha { get; set; }

    public virtual Empleados idEmpleadoNavigation { get; set; }

    public virtual Licencias idLicenciaNavigation { get; set; }
}