// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class Licencias
{
    public int idLicencia { get; set; }

    public string LicenciaNombre { get; set; }

    public int LicenciaRemunerable { get; set; }

    public virtual ICollection<Inasistencias> Inasistencias { get; set; } = new List<Inasistencias>();
}