// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class SolicitudVacaciones
{
    public int idSolicitudVacacion { get; set; }

    public int? idEmpleado { get; set; }

    public DateOnly SolicitudVacacionAprobacion { get; set; }

    public DateOnly SolicitudVacacionFechaInicio { get; set; }

    public DateOnly SolicitudVacacionFechaFin { get; set; }

    public int SolicitudVacacionDiasTotales { get; set; }

    public int SolicitudVacacionEstado { get; set; }
    [JsonIgnore]
    public virtual ICollection<AprobacionVacaciones> AprobacionVacaciones { get; set; } = new List<AprobacionVacaciones>();
    [JsonIgnore]
    public virtual Empleados idEmpleadoNavigation { get; set; }
}